### ISSUE TITLE
Can it adapt to small and medium-sized screens

### ISSUE THREAD

**Issue by wotsginger** [neoncube2/flarum-private-messages#3]
Can it adapt to small and medium-sized screens

**Comment by neoncube2** [comment]
Not yet! In fact, I think it's currently totally broken on small screens. I'm working on some fixes for this :)

**Comment by neoncube2** [comment]
This should be fixed in 1.2.0, which was just released! :)  If you run into any issues, please let me know!

**Comment by neoncube2** [comment]
I had to pull version 1.2.0 because it was letting people view other people's messages, so I'm reopening this.

**Comment by wotsginger** [comment]
Waiting for new version🤔

**Comment by neoncube2** [comment]
Thanks for the nag -- I've just released v1.2.1, which should fix this :)

**Comment by SKevo18** [comment]
According to an user at FreeFlarum, this issue does not seem to be fixed yet. This seems to happen when the message is too long, and the text overflows.

Maybe a toggleable sidebar (hamburger menu) should improve the mobile design?

**Comment by neoncube2** [comment]
I've just released v1.3.0, which should vastly improve mobile support! :)  Please give it a try and let me know if you find any issues!

**Comment by crazysvn** [comment]
seems v1.3.0 was not released? still 1.2.1 and mobile view issues still exists.
