### ISSUE TITLE
Can't see what was typed on mobile

### ISSUE THREAD

**Issue by SKevo18** [neoncube2/flarum-private-messages#6]
A FreeFlarum user had informed me that they can only see what they typed on the desktop version, but not mobile.

PHP Flarum info:

```
Flarum core: 1.8.5
PHP version: 8.3.10
MySQL version: 11.4.3-MariaDB-ubu2204
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+-----------------------------------+---------+--------+
| Flarum Extensions                 |         |        |
+-----------------------------------+---------+--------+
| ID                                | Version | Commit |
+-----------------------------------+---------+--------+
| flarum-flags                      | v1.8.0  |        |
| flarum-tags                       | v1.8.1  |        |
| flarum-approval                   | v1.8.1  |        |
| flarum-suspend                    | v1.8.1  |        |
| flarum-mentions                   | v1.8.3  |        |
| flarum-subscriptions              | v1.8.0  |        |
| fof-sitemap                       | 2.2.1   |        |
| v17development-seo                | v1.8.1  |        |
| flarum-sticky                     | v1.8.0  |        |
| flarum-lock                       | v1.8.0  |        |
| flarum-markdown                   | v1.8.0  |        |
| fof-formatting                    | 1.0.3   |        |
| fof-merge-discussions             | 1.4.1   |        |
| flarum-likes                      | v1.8.0  |        |
| afrux-forum-widgets-core          | v0.1.7  |        |
| fof-user-directory                | 1.3.3   |        |
| fof-follow-tags                   | 1.2.6   |        |
| fof-oauth                         | 1.6.10  |        |
| yannisme-oxotheme                 | 2.1.8   |        |
| webbinaro-calendar                | 1.7.0   |        |
| v17development-blog               | v0.7.7  |        |
| tohsakarat-table-of-content       | v1.1.1  |        |
| therealsujitk-gifs                | v4.1.1  |        |
| the-turk-flamoji                  | 1.0.4   |        |
| the-turk-diff                     | 1.1.2   |        |
| sycho-profile-cover               | v1.3.5  |        |
| sycho-move-posts                  | v0.1.7  |        |
| sycho-lite-youtube                | v0.1.1  |        |
| rob006-last-post-avatar           | 1.2.4   |        |
| ramesh-dada-download-button       | v8.1.4  |        |
| neoncube-private-messages         | 1.2.0   |        |
| nearata-internal-links-noreload   | v2.2.0  |        |
| nearata-embed-video               | 3.3.2   |        |
| migratetoflarum-canonical         | 1.0.0   |        |
| michaelbelgium-discussion-views   | v7.3    |        |
| malago-achievements               | 0.5.6   |        |
| litalino-more-bbcode              | 2.0.0   |        |
| justoverclock-welcomebox          | 2.0.2   |        |
| justoverclock-edit-posts          | 0.1.1   |        |
| justoverclock-dontgoaway          | 0.2.5   |        |
| justoverclock-contactme           | 0.2.3   |        |
| imdong-spam-alert                 | v0.0.1  |        |
| ianm-level-ranks                  | 1.1.1   |        |
| ianm-follow-users                 | 1.4.8   |        |
| foskym-oauth-center               | v1.3.0  |        |
| foskym-custom-levels              | v3.4.0  |        |
| fof-user-bio                      | 1.4.0   |        |
| fof-upload                        | 1.5.5   |        |
| fof-subscribed                    | 1.1.4   |        |
| fof-split                         | 1.1.1   |        |
| fof-socialprofile                 | 1.1.6   |        |
| fof-share-social                  | 1.2.0   |        |
| fof-secure-https                  | 1.1.3   |        |
| fof-reactions                     | 1.4.1   |        |
| fof-profile-image-crop            | 1.1.6   |        |
| fof-polls                         | 1.4.2   |        |
| fof-links                         | 1.2.3   |        |
| fof-frontpage                     | 1.2.0   |        |
| fof-forum-statistics-widget       | 1.2.1   |        |
| fof-default-user-preferences      | 1.2.1   |        |
| fof-default-group                 | 1.1.2   |        |
| fof-byobu                         | 1.3.6   |        |
| fof-bbcode-tabs                   | 1.0.3   |        |
| fof-bbcode-details                | 1.1.2   |        |
| fof-ban-ips                       | 1.1.1   |        |
| fof-anti-spam                     | 1.1.2   |        |
| fof-analytics                     | 1.1.0   |        |
| flarum-statistics                 | v1.8.0  |        |
| flarum-pusher                     | v1.8.0  |        |
| flarum-nicknames                  | v1.8.0  |        |
| flarum-lang-swedish               | 1.1.1   |        |
| flarum-lang-spanish               | 1.9.0   |        |
| flarum-lang-italian               | 1.11.0  |        |
| flarum-lang-german                | 1.13.0  |        |
| flarum-lang-french                | v4.25.0 |        |
| flarum-lang-english               | v1.8.0  |        |
| flarum-emoji                      | v1.8.0  |        |
| flarum-embed                      | v1.8.0  |        |
| flarum-bbcode                     | v1.8.0  |        |
| davwheat-custom-sidenav-links     | 1.0.1   |        |
| datlechin-signup-button           | v0.1.1  |        |
| datlechin-scroll-buttons          | v1.1.0  |        |
| datlechin-posted-on               | v0.2.1  |        |
| datlechin-oauth-spotify           | v0.1.0  |        |
| dalez-fluent-flarum               | v1.3.1  |        |
| clarkwinkelmann-status            | 1.0.0   |        |
| clarkwinkelmann-post-permissions  | 1.0.0   |        |
| clarkwinkelmann-group-list        | 1.0.0   |        |
| clarkwinkelmann-create-user-modal | 1.3.1   |        |
| clarkwinkelmann-circle-groups     | 1.0.1   |        |
| blomstra-welcome-login            | 0.1.0   |        |
| blomstra-mark-unread              | 0.2.0   |        |
| betterflarum-nextadmintheme       | v2.0.0  |        |
| askvortsov-checklist              | v1.3.1  |        |
| askvortsov-categories             | v3.1.0  |        |
| antoinefr-bbcode-fa               | v1.0.0  |        |
| afrux-top-posters-widget          | v0.1.4  |        |
| afrux-forum-stats-widget          | v0.1.1  |        |
| acpl-mobile-tab                   | 1.4.4   |        |
| 2nrwls-audio                      | v3.0    |        |
+-----------------------------------+---------+--------+
Base URL: https://xxx
Installation path: /data/host/xxx
Queue driver: sync
Session driver: file
Scheduler status: Never run
Mail driver: mail
Debug mode: off
```

**Comment by neoncube2** [comment]
I've just released v1.2.1, which should fix this :)

**Comment by SKevo18** [comment]
Thanks for the prompt fix, however the user had just provided more context and it turns out this is the same issue as #3 (which wasn't fixed yet). Sorry for not being more specific from the start.

**Comment by neoncube2** [comment]
@SKevo18 No worries! :)
